export const TEXT_FIELD_TYPES = [
    'text',
    'email',
    'number',
    'integer',
    'password',
    'search',
    'tel',
    'url',
    'date',
    'datetime-local',
    'month',
    'time',
    'week',
    'currency',
]