export type BadgeProgress = 'incomplete' | 'partiallyComplete' | 'complete'
export type BadgeSize = 'medium' | 'large'
export type BadgeTone =
    | 'info'
    | 'success'
    | 'warning'
    | 'critical'
    | 'attention'
    | 'new'
    | 'info-strong-experimental'
    | 'success-strong-experimental'
    | 'warning-strong-experimental'
    | 'critical-strong-experimental'
    | 'attention-strong-experimental'
    | 'read-only-experimental'
    | 'enabled-experimental'
