export type TextAs = 'dt' | 'dd' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span' | 'strong' | 'legend'
export type TextAlignment = 'start' | 'center' | 'end' | 'justify'
export type TextVariant = 'headingSm' | 'headingMd' | 'headingLg' | 'headingXl' | 'heading2xl' | 'heading3xl' | 'bodySm' | 'bodyMd' | 'bodyLg'
export type TextWeight = 'regular' | 'medium' | 'semibold' | 'bold'
export type TextTone = 'success' | 'critical' | 'caution' | 'subdued' | 'text-inverse'
export type TextDecorationLine = 'line-through'