export type Breakpoints = 'xs' | 'sm' | 'md' | 'lg' | 'xl'
export type SpaceScale = '0' |
    '025' |
    '050' |
    '100' |
    '150' |
    '200' |
    '300' |
    '400' |
    '500' |
    '600' |
    '800' |
    '1000' |
    '1200' |
    '1600' |
    '2000' |
    '2400' |
    '2800' |
    '3200'

export type Backgrounds =
    'bg-inverse'
    // | 'bg-surface-active'
    // | 'bg-surface-brand-active'
    // | 'bg-surface-brand-hover'
    // | 'bg-surface-brand-selected'
    // | 'bg-surface-brand'
    // | 'bg-surface-caution-active'
    // | 'bg-surface-caution-hover'
    | 'bg-surface-caution'
    // | 'bg-surface-critical-active'
    // | 'bg-surface-critical-hover'
    | 'bg-surface-critical'
    // | 'bg-surface-disabled'
    // | 'bg-surface-emphasis-active'
    // | 'bg-surface-emphasis-hover'
    | 'bg-surface-emphasis'
    // | 'bg-surface-hover'
    // | 'bg-surface-info-active'
    // | 'bg-surface-info-hover'
    | 'bg-surface-info'
    | 'bg-surface-inverse'
    // | 'bg-surface-magic-active'
    // | 'bg-surface-magic-hover'
    // | 'bg-surface-magic'
    // | 'bg-surface-secondary-active'
    // | 'bg-surface-secondary-hover'
    // | 'bg-surface-secondary-selected'
    // | 'bg-surface-secondary'
    // | 'bg-surface-selected'
    // | 'bg-surface-success-active'
    // | 'bg-surface-success-hover'
    | 'bg-surface-success'
    // | 'bg-surface-tertiary-active'
    // | 'bg-surface-tertiary-hover'
    // | 'bg-surface-tertiary'
    | 'bg-surface-transparent'
    // | 'bg-surface-warning-active'
    // | 'bg-surface-warning-hover'
    | 'bg-surface-warning'
    | 'bg-surface'
    // | 'bg'
    // 'bg-fill-active'
    // | 'bg-fill-brand-active'
    // | 'bg-fill-brand-disabled'
    // | 'bg-fill-brand-hover'
    // | 'bg-fill-brand-selected'
    // | 'bg-fill-brand'
    // | 'bg-fill-caution-active'
    // | 'bg-fill-caution-hover'
    // | 'bg-fill-caution-secondary'
    // | 'bg-fill-caution'
    // | 'bg-fill-critical-active'
    // | 'bg-fill-critical-hover'
    // | 'bg-fill-critical-secondary'
    // | 'bg-fill-critical-selected'
    // | 'bg-fill-critical'
    // | 'bg-fill-disabled'
    // | 'bg-fill-emphasis-active'
    // | 'bg-fill-emphasis-hover'
    // | 'bg-fill-emphasis'
    // | 'bg-fill-hover'
    // | 'bg-fill-info-active'
    // | 'bg-fill-info-hover'
    // | 'bg-fill-info-secondary'
    // | 'bg-fill-info'
    // | 'bg-fill-inverse-active'
    // | 'bg-fill-inverse-hover'
    // | 'bg-fill-inverse'
    // | 'bg-fill-magic-secondary-active'
    // | 'bg-fill-magic-secondary-hover'
    // | 'bg-fill-magic-secondary'
    // | 'bg-fill-magic'
    // | 'bg-fill-secondary-active'
    // | 'bg-fill-secondary-hover'
    // | 'bg-fill-secondary'
    // | 'bg-fill-selected'
    // | 'bg-fill-success-active'
    // | 'bg-fill-success-hover'
    // | 'bg-fill-success-secondary'
    // | 'bg-fill-success'
    // | 'bg-fill-tertiary-active'
    // | 'bg-fill-tertiary-hover'
    // | 'bg-fill-tertiary'
    // | 'bg-fill-transparent-active'
    // | 'bg-fill-transparent-hover'
    // | 'bg-fill-transparent-secondary-active'
    // | 'bg-fill-transparent-secondary-hover'
    // | 'bg-fill-transparent-secondary'
    // | 'bg-fill-transparent-selected'
    // | 'bg-fill-transparent'
    // | 'bg-fill-warning-active'
    // | 'bg-fill-warning-hover'
    // | 'bg-fill-warning-secondary'
    // | 'bg-fill-warning'
    // | 'bg-fill'